export const BRAND = {
  name: 'Điểm Tâm BĐS',
  fullName: 'Bất Động Sản Điểm Tâm',
  shortName: 'Điểm Tâm',
  domain: 'bdsdiemtam.com',
  email: 'bdsdiemtam@gmail.com',
  phone: '0975 982 592',
  phone2: '0983 123 306',
  address: 'TP. Hồ Chí Minh',
  slogan: 'Nơi mọi ngôi nhà tìm được chủ nhân',
  seoSuffix: '| Điểm Tâm BĐS',
  siteName: 'Điểm Tâm BĐS',
  copyright: '© 2025 Bất Động Sản Điểm Tâm. Mọi quyền được bảo lưu.',
  designedBy: 'Thiết kế bởi đội ngũ Điểm Tâm BĐS',
} as const;
